import streamlit as st
st.title("hello")
st.success('cshb')
st.markdown('hh')
st.text('hghcgc')
st.info('sb')
st.warning('sjnn')
st.error('sbjn')
ri=ZeroDivisionError('fhhgkk')
st.exception(ri)
st.code('for i in range(0,10):\n'
        '\tprint(i*2)')
st.checkbox('Male')
st.radio('select:',('boy','girl'))
st.subheader('selectbox')
st.selectbox('select',('data','scgs','xxah'))
st.multiselect('select',('ajkxba','xjbsn','xhjsjxx'))
st.button('click me')
st.slider('nxsnns',0,10,step=1)
st.header('user,pass')
st.subheader('user')
rj=st.text_input('name')
st.subheader('pass')
oi=st.text_input('pass',type='password')